export const config = {
    db: {
        host: process.env.DB_HOST || "eventivapp.cnay0qcmgf10.us-east-2.rds.amazonaws.com",
        user: process.env.DB_USER || "admin",
        password: process.env.DB_PASSWORD || "8a4aAsQ3:WHxVDtZ]R)pJ(KYtBQ?",
        database: process.env.DB_NAME || "base",
    },
    dbDurangeneidad: {
        host: process.env.DB_DGO_HOST || "eventivapp.cnay0qcmgf10.us-east-2.rds.amazonaws.com",
        user: process.env.DB_DGO_USER || "admin",
        password: process.env.DB_DGO_PASSWORD || "8a4aAsQ3:WHxVDtZ]R)pJ(KYtBQ?",
        database: process.env.DB_DGO_NAME || "dgo",
    },
    jwtSecret: process.env.JWT_SECRET || '',
    jwtExpiresIn: process.env.JWT_EXPIRES_IN || '15m',
    jwtRefreshExpiresInDays: Number(process.env.JWT_REFRESH_EXPIRES_IN_DAYS || 30),
    socketPort: Number(process.env.SOCKET_PORT || process.env.PORT || 3000),
    socketCorsOrigin: process.env.SOCKET_CORS_ORIGIN || '*',
    presenceTtlMs: Number(process.env.PRESENCE_TTL_MS || 60000),
    socketRateLimitWindowMs: Number(process.env.SOCKET_RATE_LIMIT_WINDOW_MS || 60000),
    socketRateLimitMaxEvents: Number(process.env.SOCKET_RATE_LIMIT_MAX_EVENTS || 180),
    recommendationItemsLimit: Number(process.env.RECOMMENDATION_ITEMS_LIMIT || 8),
    recommendationPackagesLimit: Number(process.env.RECOMMENDATION_PACKAGES_LIMIT || 3),
    defaultLogisticsFee: Number(process.env.DEFAULT_LOGISTICS_FEE || 0),
    listPerPage: 10,
};
