export interface IInventary {
    id_mob?: number,
    id_empresa?: number,
    cantidad_mob: number,
    nombre_mob: string,
    costo_mob: number,
    ancho_cm?: number | null,
    alto_cm?: number | null,
    fondo_cm?: number | null,
    peso_kg?: number | null,
    uso_espacio?: 'indoor' | 'outdoor' | 'both' | null,
    estilo?: string | null,
    color?: string | null,
    material?: string | null,
    extra_mob?: string,
    extra_mob_costo?: number,
    ruta_imagen?: string,
    eliminado?: number,
    fkid_inventario?: number,
    cantidad?: number
}