export interface IPayments {
    id_evento: 848,
    id_empresa: 1,
    nombre_evento: string,
    tipo_evento: string,
    fecha_envio_evento: string,
    hora_envio_evento: string,
    fecha_recoleccion_evento: string,
    hora_recoleccion_evento: string,
    pagado_evento: number,
    nombre_titular_evento: string,
    direccion_evento: string,
    telefono_titular_evento: string,
    observaciones: string,
    entregado: number,
    recolectado: number,
    descuento: number,
    iva: number,
    flete: number,
    fecha_creacion: string,
    id_pago: number,
    costo_total: number,
    saldo: number,
    anticipo: number
}