export const API_EVENTS = '/events'
export const API_AUTH = '/auth'
export const API_INVENTARY = '/inventary'
export const API_WORKERS = '/workers'
export const API_CLIENTS = '/clients'
export const API_PAYMENTS = '/payments'

export const GET_EVENTS_PATH = API_EVENTS + '/getEvents'
export const GET_EVENTS_DAY_PATH = API_EVENTS + '/getEventsDay'
export const GET_DETAILS_EVENT_PATH = API_EVENTS + '/getDetail'
export const GET_AVAILABLE_DAY_PATH = API_EVENTS + '/available'
export const CREATE_EVENT = API_EVENTS + '/add'
export const ADD_OBS = API_EVENTS + '/observaciones'
export const STATUS_DELIVERY = API_EVENTS + '/status'
export const ADD_ITEMS = API_EVENTS + '/additems'
export const REMOVE_EVENT = API_EVENTS + '/remove'
export const REMOVE_ITEM = API_EVENTS + '/removeitem'

export const LOGIN_PATH = API_AUTH + '/login'

export const GET_INVENTARY = API_INVENTARY + '/getInventary'
export const ADD_INVENTARY = API_INVENTARY + '/addInventary'
export const UPDATE_INVENTARY = API_INVENTARY + '/updateInventary'
export const REMOVE_INVENTARY = API_INVENTARY + '/removeInventary'
export const GET_PACKAGES = API_INVENTARY + '/getPackages'
export const REMOVE_PACKAGES = API_INVENTARY + '/removePackage'
export const ADD_PACKAGES = API_INVENTARY + '/addPackages'

export const GET_WORKERS = API_WORKERS + '/getWorkers'
export const ADD_WORKER = API_WORKERS + '/addWorker'
export const REMOVE_WORKER = API_WORKERS + '/remove'
export const EDIT_WORKER = API_WORKERS + '/editWorker'
export const ACTIVE_WORKER = API_WORKERS + '/active'
export const GET_WORKERS_EVENTS = API_WORKERS + '/getEventsDay'

export const GET_CLIENTS = API_CLIENTS + '/getClients'

export const GET_PAYMENTS = API_PAYMENTS + '/getPayments'
export const ADD_PAYMENTS = API_PAYMENTS + '/addPayment'
