use_modular_headers!

$RNFirebaseAsStaticFramework = true

pod 'GoogleMaps', '9.3.0'
pod 'Google-Maps-iOS-Utils', '6.1.0'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.0'
prepare_react_native_project!

flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Mobiliaria' do
  # Configurar uso de frameworks como estáticos
  use_frameworks! :linkage => :static

  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    #:flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'MobiliariaTests' do
    inherit! :complete
    # Pods para testing
  end

  post_install do |installer|
    # Deshabilitar Bitcode en todas las dependencias
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['BITCODE_GENERATION_MODE'] = 'marker' # Para evitar problemas en App Store Connect
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
        # En Apple Silicon, excluir arm64 en simulator impide seleccionar destinos iOS Simulator.
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = ''

        # Xcode 26 marca como deprecado el espacio en user-defined literals usado por Yoga de RN 0.72.
        # Lo desactivamos solo para compilar dependencias legacy sin tocar node_modules.
        if target.name == 'Yoga'
          cxxflags = config.build_settings['OTHER_CPLUSPLUSFLAGS'] || '$(inherited)'
          cxxflags = "#{cxxflags} -Wno-deprecated-literal-operator" unless cxxflags.include?('-Wno-deprecated-literal-operator')
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] = cxxflags
        end
      end
    end

    # Deshabilitar Bitcode en Hermes
    installer.pods_project.targets.each do |target|
      if target.name == 'hermes' || target.name.start_with?('hermes')
        target.build_configurations.each do |config|
          config.build_settings['ENABLE_BITCODE'] = 'NO'
          config.build_settings['BITCODE_GENERATION_MODE'] = 'marker'
        end
      end
    end

    # Configuración necesaria para React Native
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
